### ISSUE TITLE
Path handling enhancement: Improve the handling of filepaths to work with and without devon ide

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-forge/tutorial-compiler#87]
Currently the paths in the commands are related to 'devonfw/workspaces/main'. However, in some tutorials it is not necessary to install ide before starting the other steps. So the commands should work without ide, too.
The idea is to set an environment variable in the installDevonfwIde step. If the variable is set, the following steps will use it in their paths. If no ide is installed, the paths that the playbook specifies are used.

**Comment by denise-khuu** [comment]
* All the maven commands have to be either 'mvn' or 'devon mvn', otherwise runServer() won't work. (They create and work on different file-structures)

`mvn clean install` & `mvn spring-boot:run`
`devon mvn clean install` & `devon mvn spring-boot:run`

* For enhancement we can also remove the cdCommand in Katacodas createFile. Creating a new file works independently from the current folder position in the terminal. 

* In addition one has to add path.join() to the definition of currentDir and to the assignment in installDevonfwIde. 

In cloneRepository for example we start at 
`currentDir = "/root"`.
On windows by using 
`changeCurrentDir(path.join(path))` 
we get a path with backslashes.
In dirUtil we compare "/root" with "root", since we have split the paths at backslashes, which leads to the a wrong cdCommand.
